# SQL Analysis

This notebook uses SQL queries to explore the cleaned used-car database stored in SQLite.

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/cars.db")

In [2]:
query1 = """
SELECT 
	brand,
	COUNT(*) as n_cars
FROM cars
GROUP BY brand
ORDER BY n_cars DESC
LIMIT 10;
"""

pd.read_sql_query(query1, conn)

           brand  n_cars
0           Ford     386
1            BMW     375
2  Mercedes-Benz     315
3      Chevrolet     292
4        Porsche     201
5           Audi     200
6         Toyota     199
7          Lexus     163
8           Jeep     143
9           Land     130

Ford has the highest number of listings in the dataset, with 386 vehicles, followed by BMW with 375 vehicles.

In [3]:
query2 = """
SELECT
	fuel_type,
	COUNT(*) AS n_cars,
    ROUND(AVG(price), 2) AS average_price
FROM cars
GROUP BY fuel_type
HAVING COUNT(*) >= 30
ORDER BY average_price DESC;
"""

pd.read_sql_query(query2, conn)

        fuel_type  n_cars  average_price
0          Hybrid     194       51426.20
1         Unknown     217       50169.61
2          Diesel     116       48695.42
3  Plug-In Hybrid      34       45946.18
4        Gasoline    3309       44538.53
5   E85 Flex Fuel     139       22744.12

Among fuel types with at least 30 listings, Hybrid had the highest average listed price at about 51426, while E85 Flex Fuel had the lowest average price at approximately 22744.

In [4]:
query3 = """
SELECT 
	accident,
	COUNT(*) AS n_cars,
	ROUND(AVG(price), 2) AS average_price
FROM cars
GROUP BY accident
ORDER BY average_price DESC;
"""

pd.read_sql_query(query3, conn)

                                 accident  n_cars  average_price
0                                 Unknown     113       50788.39
1                           None reported    2910       49638.07
2  At least 1 accident or damage reported     986       28831.50

Vehicles with reported accident or damage history had a lower average listed price than vehicles with no reported accidents.

In [5]:
query4 = """
SELECT
	transmission_group,
	COUNT(*) AS n_cars,
	ROUND(AVG(price), 2) AS average_price
FROM cars
GROUP BY transmission_group
HAVING COUNT(*) >= 50
ORDER BY average_price DESC;
"""

pd.read_sql_query(query4, conn)

  transmission_group  n_cars  average_price
0         Dual Shift     398       54710.62
1          Automatic    3110       43894.59
2             Manual     374       41442.97
3                CVT     100       23528.84

Dual Shift has highest average listed price at approximately 54711. However, automatic has by far the most listings, with 3110 vehicles, and has the second-highest average listed price at 43895.

In [6]:
query5 = """
SELECT
    brand,
    COUNT(*) AS n_cars,
    ROUND(AVG(price), 2) AS average_price
FROM cars
WHERE model_year >= 2020
GROUP BY brand
HAVING COUNT(*) >= 20
ORDER BY average_price DESC;
"""

pd.read_sql_query(query5, conn)

            brand  n_cars  average_price
0         Porsche      51      124579.04
1   Mercedes-Benz      75       95153.91
2        Cadillac      29       92253.17
3            Land      53       89484.30
4             BMW     108       69028.16
5            Audi      54       63757.89
6           Lexus      45       63103.73
7       Chevrolet      94       60351.74
8             GMC      30       59811.90
9           Tesla      55       53771.29
10           Ford     135       52162.16
11          Dodge      22       49864.05
12            RAM      45       48899.53
13         Toyota      60       48449.95
14           Jeep      63       46188.90
15          Acura      20       44031.50
16         Nissan      27       41275.70
17            Kia      48       35249.81
18        Hyundai      23       31885.43
19          Mazda      25       29410.96

Porsche has the highest average listed price at approximately 124579, followed by Mercedes-Benz at 95154.

In [7]:
query6 = """
SELECT brand, model, model_year, mileage, price
FROM cars
WHERE model_year >= 2020
  AND mileage >= 100000
ORDER BY mileage DESC
LIMIT 15;
"""

pd.read_sql_query(query6, conn)

       brand                     model  model_year  mileage  price
0        RAM  ProMaster 3500 High Roof        2021   147834  32662
1  Chevrolet             Tahoe Premier        2020   137000  46000
2      Honda               Civic Sport        2020   121212  18387
3   Cadillac       Escalade ESV Luxury        2020   120000  55000
4       Ford        Transit Connect XL        2020   119000  18000
5        Kia                K5 GT-Line        2021   100312  19980

Several vehicles from 2020 or later have mileage above 100000 miles.

In [8]:
query7 = """
SELECT brand, model, model_year, mileage, price
FROM cars
WHERE model_year >= 2020
  AND mileage < 30000
  AND price BETWEEN 20000 AND 40000
ORDER BY price ASC
LIMIT 15;
"""

pd.read_sql_query(query7, conn)

        brand                     model  model_year  mileage  price
0        Ford              Explorer XLT        2020    17000  21000
1         Kia             Forte GT-Line        2021    24534  21900
2   Chevrolet            Trailblazer LS        2021    24965  22995
3   Chevrolet            Trailblazer LS        2021    20497  22999
4      Nissan             Altima 2.5 SV        2020    22295  23599
5       Honda               Civic Sport        2020    23131  23739
6      Toyota                   C-HR LE        2021    13180  23998
7     Hyundai       Elantra HEV Limited        2021    28600  23999
8         Kia             Forte GT-Line        2022    14950  24000
9         Kia             Forte GT-Line        2023    15500  24500
10      Honda               Civic Sport        2022    25420  24500
11      Mazda                CX-30 Base        2020    19319  24899
12        Kia                Sportage S        2021    16949  24995
13     Subaru           Impreza Premium        2022    10419  24998
14    Hyundai  IONIQ Plug-In Hybrid SEL        2022    13044  24999

These listings may represent relatvively affordable options among newer vehicles with lower mileage.

In [9]:
conn.close()